const merchantOnboardingFieldList = {
  content: {
    merchantTypes: [
      {
        value: "SMALL",
        displayName: "Small",
      },
      {
        value: "LARGE",
        displayName: "Large",
      },
    ],
    ownershipTypes: [
      {
        value: "PARTNERSHIP",
        displayName: "Partnership",
      },
      {
        value: "OTHERS",
        displayName: "Others",
      },
      {
        value: "PUBLIC",
        displayName: "Public",
      },
      {
        value: "PROPRIETARY",
        displayName: "Proprietary",
      },
      {
        value: "PRIVATE",
        displayName: "Private",
      },
    ],
    merchantGenres: [
      {
        value: "OFFLINE",
        displayName: "Offline",
      },
      {
        value: "ONLINE",
        displayName: "Online",
      },
    ],
    onBoardingTypes: [
      {
        value: "BANK",
        displayName: "Bank",
      },
      {
        value: "MERCHANT",
        displayName: "Merchant",
      },
      {
        value: "CORPORATE",
        displayName: "Corporate",
      },
      {
        value: "AGGREGATOR",

        value: "CURRENT",
        displayName: "Current",
      },
      {
        value: "SAVINGS",
        displayName: "Savings",
      },
    ],
    ownerTypes: [
      {
        value: "OWNER",
        displayName: "Owner",
      },
      {
        value: "DIRECTOR",
        displayName: "Director",
      },
      {
        value: "PROMOTER",
        displayName: "Promoter",
      },
      {
        value: "PARTNER",
        displayName: "Partner",
      },
    ],
    businessCategory: [
      {
        value: "AUTOMOTIVE",
        displayName: "Automotive",
      },
      {
        value: "CAR_RENTALS",
        displayName: "Car Rentals",
      },
      {
        value: "DINING_AND_ENTERTAINMENT",
        displayName: "Dining & Entertainment",
      },
      {
        value: "EDUCATION_AND_SOCIAL_SERVICES",
        displayName: "Education & Social Services",
      },
      {
        value: "GOVERNMENT_AND_LEGAL",
        displayName: "Government & Legal",
      },
      {
        value: "HEALTH_AND_WELLNESS",
        displayName: "Health & Wellness",
      },
      {
        value: "MISCELLANEOUS",
        displayName: "Miscellaneous",
      },
      {
        value: "PROFESSIONAL_AND_BUSINESS_SERVICES",
        displayName: "Professional & Business Services",
      },
      {
        value: "RETAIL_AND_SHOPPING",
        displayName: "Retail & Shopping",
      },
      {
        value: "TRANSPORTATION",
        displayName: "Transportation",
      },
      {
        value: "TRAVEL_AND_HOSPITALITY",
        displayName: "Travel & Hospitality",
      },
      {
        value: "UTILITIES_AND_COMMUNICATION",
        displayName: "Utilities & Communication",
      },
    ],
  },
};

const subCategoriesList = {
  content: {
    subCategories: [
      "HOLIDAY INN EXPRESS",
      "BEST WESTERN HOTELS",
      "SHERATON HOTELS",
      "HILTON HOTELS",
      "FORTE HOTELS",
      "GOLDEN TULIP HOTELS",
      "FRIENDSHIP INNS",
      "QUALITY INNS",
      "MARRIOTT HOTELS",
      "DAYS INNS",
      "ARABELLA HOTELS",
      "INTER-CONTINENTAL HOTELS",
      "WESTIN HOTELS",
      "AMERISUITES",
      "RODEWAY INNS",
      "LA QUINTA MOTOR INNS",
      "AMERICANA HOTELS",
      "SOL HOTELS",
      "PULLMAN INTL HOTELS PULLMAN INTERNATIONALHOTELS",
      "MERIDIEN HOTELS",
      "TOKYO HOTEL",
      "PENINSULA HOTEL",
      "WELCOMGROUP HOTELS",
      "DUNFEY HOTELS",
      "PRINCE HOTELS",
      "DOWNTOWNER-PASSPORT HOTEL",
      "RED LION HOTELS",
      "CP HOTELS",
      "RENAISSANCE HOTELS",
      "SOUTH SEAS RESORT",
      "CANYON RANCH",
      "KAHALA MANDARIN ORIENTAL HOTEL",
      "THE ORCHID AT MAUNA LANI",
      "HALEKULANI HOTEL/WAIKKI PARC",
      "PRIMADONNA HOTEL & CASINO",
      "WHISKEY PETE&S HOTEL & CASINO",
      "CHATEAU ELAN WINERY & RESORT",
      "BEAU RIVAGE HOTEL & CASINO",
      "BELLAGIO",
      "HOTEL IBIS",
      "SOUTHERN PACIFIC HOTELS",
      "HILTON INTERNATIONALS",
      "AMFAC HOTELS",
      "ANA HOTEL",
      "CONCORDE HOTELS",
      "SUMMERFIELD SUITES HOTEL",
      "IBEROTEL HOTELS",
      "HOTEL OKURA",
      "ROYAL HOTELS",
      "FOUR SEASONS HOTELS",
      "CIGA HOTELS",
      "SHANGRI-LA INTL HOTELS SHANGRI-LA INTERNATIONAL",
      "SIERRA SUITES HOTELS",
      "HOTELS MELIA",
      "AUBERGE DES GOVERNEURS",
      "REGAL & INNS",
      "MIRAGE HOTEL AND CASINO",
      "COAST HOTELS",
      "PARK INNS INTERNATIONAL",
      "TREASURE ISLAND HOTEL & CASINO",
      "JOLLY HOTELS",
      "GOLDEN NUGGET",
      "COMFORT INNS",
      "JOURNEY'S END MOTELS",
      "SAMZES TOWN HOTEL & CASINO",
      "RELAX INNS",
      "LADBROKE HOTELS",
      "FORUM HOTELS",
      "MIYAKO HOTELS",
      "SANDMAN HOTELS",
      "VENTURE INNS",
      "VAGABOND HOTELS",
      "MANDARIN ORIENTAL HOTEL",
      "HOTEL MERCURE",
      "DELTA HOTEL",
      "CALIFORNIA HOTEL & CASINO",
      "SAS HOTELS",
      "PRINCESS HOTELS INTL PRINCESS HOTELS INTERNATIONAL",
      "HUNGAR HOTELS",
      "SOKOS HOTELS",
      "DORAL HOTELS",
      "HELMSLEY HOTELS",
      "FAIRMONT HOTELS",
      "SONESTA HOTELS",
      "OMNI HOTELS",
      "CUNARD HOTELS",
      "HOSPITALITY INNS",
      "REGENT INTL HOTELS REGENT INTERNATIONAL HOTELS",
      "PANNONIA HOTELS",
      "NOAH/ES HOTELS",
      "MOVENPICK HOTELS",
      "TRAVELODGE",
      "BINION/ES HORSESHOE CLUB",
      "MERLIN HOTELS",
      "DORINT HOTELS",
      "LADY LUCK HOTEL AND CASINO",
      "HOTEL UNIVERSALE",
      "EXCALIBUR AND CASINO",
      "DAN HOTELS",
      "SLEEP INNS",
      "THE PHOENICIAN",
      "RANK HOTEL",
      "SWISSOTEL",
      "RESO HOTELS",
      "SAROVA HOTELS",
      "RAMADA INNS",
      "HOWARD JOHNSON",
      "MOUNT CHARLOTTE THISTLE",
      "HYATT HOTELS",
      "SOFITEL HOTELS",
      "NOVOTEL HOTELS",
      "STEIGENBERGER HOTELS",
      "ECONO LODGES",
      "QUEENS MOAT HOUSES",
      "SWALLOW HOTELS",
      "HUSA HOTELS",
      "DE VERAE HOTELS",
      "RADISSON HOTELS",
      "RED ROOF INNS",
      "IMPERIAL LONDON HOTEL",
      "EMBASSY HOTELS",
      "PENTA HOTELS",
      "LOEWS HOTELS",
      "SCANDIC HOTELS",
      "SARA HOTELS",
      "OBEROI HOTELS",
      "OTANI HOTELS",
      "TAI HOTELS INTERNATIONAL",
      "KNIGHTS INNS",
      "METROPOLE HOTELS",
      "CIRCUS CIRCUS HOTEL & CASINO",
      "HOTELES EL PRESIDENTE",
      "FLAG INN",
      "HAMPTON INNS",
      "STAKIS HOTELS",
      "LUXOR HOTEL AND CASINO",
      "MARTIM HOTELS",
      "ELDORADO HOTEL AND CASINO",
      "ARCADE HOTELS",
      "ARCTIA HOTELS",
      "CAMPANILE HOTELS",
      "IBUSZ HOTELS",
      "RANTASIPI HOTELS",
      "INTERHOTEL CEDOK",
      "MONTE CARLO HOTEL & CASINO",
      "CLIMAT DE FRANCE HOTELS",
      "CUMULUS HOTELS",
      "SILVER LEGACY & CASINO",
      "HOTEIS OTHAN",
      "ADAMS MARK HOTELS",
      "SAHARA HOTEL AND CASINO",
      "BRADBURY SUITES",
      "BUDGET HOST INN",
      "BUDGETEL HOTELS",
      "SUISSE CHALETS",
      "CLARION HOTELS",
      "COMPRI HOTELS",
      "CONSORT HOTELS",
      "COURTYARD BY MARRIOTT",
      "DILLON INNS",
      "DOUBLETREE HOTELS",
      "DRURY INNS",
      "ECONOMY INNS OF AMERICA",
      "EMBASSY SUITES",
      "EXEL INNS",
      "FAIRFIELD HOTELS",
      "HARLEY HOTELS",
      "MIDWAY MOTOR LODGE",
      "MOTEL 6",
      "LA MANSION DEL RIO HOTEL",
      "THE REGISTRY HOTEL",
      "RESIDENCE INNS",
      "ROYCE HOTELS",
      "SANDMAN INNS",
      "SHILO INNS",
      "SHONEY'S INNS",
      "VIRGIN RIVER HOTEL & CASINO",
      "SUPER & MOTELS",
      "THE RITZ CARLTON HOTELS",
      "FLAG INNS (AUSTRALIA)",
      "BUFFALO BILLES HOTEL & CASINO",
      "QUALITY PACIFIC HOTEL",
      "FOUR SEASONS HOTEL(AUSTRALIA)",
      "FAIRFIELD INN",
      "CARLTON HOTELS",
      "CITY LODGE HOTELS",
      "KAROS HOTELS",
      "PROTEA HOTELS",
      "SOUTHERN SUN HOTELS",
      "CONRAD",
      "WYNDHAM HOTELS",
      "RICA HOTELS",
      "INTER NOR HOTELS",
      "SEAPINES PLANTATION",
      "RIO SUITES",
      "BROADMOOR HOTEL",
      "BALLYES HOTEL AND CASINO",
      "JOHN ASCUAGAES NUGGET",
      "MGM GRAND HOTEL",
      "HARRAHES HOTELS AND CASINOS",
      "OPRYLAND HOTEL",
      "BOCA RATON RESORT",
      "HARVEY/BRISTOL HOTEL",
      "MASTERS ECONOMY INNS",
      "COLORADO BELLE/EDGEWATER",
      "RIVIERA HOTEL AND CASINO",
      "TROPICANA RESORT & CASINO",
      "WOODSIDE HOTELS & RESORT",
      "TOWNPLACE SUITES",
      "MILLENNIUM BROADWAY HOTEL",
      "CLUB MED",
      "BILTMORE HOTEL & SUITES",
      "CAREFREE RESORTS",
      "ST REGIS HOTEL",
      "THE ELIOT HOTEL",
      "CLUBCORP/CLUB RESORTS",
      "WELLESLAY INNS",
      "BEVERLY HILLS HOTELS",
      "CROWNE PLAZA HOTEL",
      "HOMEWOOD SUITES",
      "PEABODY HOTELS",
      "GREENBRIAR HOTELS",
      "AMELIA ISLAND",
      "THE HOMESTEAD",
      "FREMONT HOTEL AND CASINO",
      "MAIN STREET HOTEL & CASINO",
      "SILVER STAR HOTEL & CASINO",
      "STRATOSPHERE HOTEL AND CASINO",
      "SPRINGHILL SUITES",
      "CEASARS HOTEL AND CASINO",
      "NEMACOLIN WOODLANDS",
      "VENETIAN RESORT HOTEL & CASINO",
      "NEW YORK NY HOTEL & CASINO",
      "OCEAN DUNES RESORT AND VILLAS",
      "NEVELE GRANDE RESORT & COUNTRY CLUB",
      "MANDALAY BAY RESORT",
      "DISNEYLAND HOTELS",
      "Hotels",
      "Timeshares",
      "Sporting/Recreation Camps",
      "Trailer Parks",
    ],
  },
};

exports.getMerchantOnboardingFieldList = async (req, res) => {
  try {
    res.status(200).json(merchantOnboardingFieldList);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Internal server error" });
  }
};

exports.getSubCategoriesList = async (req, res) => {
  try {
    res.status(200).json(subCategoriesList);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Internal server error" });
  }
};
